import { useState } from 'react'
import { supabase } from '../lib/supabase'
import { createInAppNotification } from '../lib/notify'
import { useAuth } from '../contexts/AuthContext'

type SummaryType = 'full' | 'doctor' | 'mcas' | 'medication' | 'pain'

export function AiSummariesPage () {
  const { user } = useAuth()
  const [days, setDays] = useState(30)
  const [type, setType] = useState<SummaryType>('full')
  const [text, setText] = useState('')
  const [busy, setBusy] = useState(false)
  const [meta, setMeta] = useState<{ aiEnabled?: boolean } | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function run () {
    if (!user) return
    setBusy(true)
    setError(null)
    setText('')
    setMeta(null)

    const { data, error: fnError } = await supabase.functions.invoke('ai-summary', {
      body: { summaryType: type, days },
    })

    setBusy(false)

    if (fnError) {
      setError(fnError.message)
      return
    }

    const payload = data as { summary?: string; error?: string; aiEnabled?: boolean }
    if (payload?.error) {
      setError(payload.error)
      return
    }

    setText(payload.summary ?? '')
    setMeta({ aiEnabled: payload.aiEnabled })

    await createInAppNotification(
      user.id,
      'AI summary ready',
      `${type} summary (${days}d) generated.`,
      'ai',
    )
  }

  function downloadTxt () {
    const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = `medical-summary-${type}-${days}d.txt`
    a.click()
    URL.revokeObjectURL(a.href)
  }

  return (
    <div>
      <div className="card">
        <h2 style={{ marginTop: 0 }}>AI summaries</h2>
        <p className="muted">
          Narrative summaries are generated by an Edge Function using your own rows. This is not medical advice — bring outputs to your clinician.
        </p>

        <div className="form-row">
          <div className="form-group">
            <label>Window (days)</label>
            <input
              type="number"
              min={1}
              max={365}
              value={days}
              onChange={(e) => setDays(Number(e.target.value) || 30)}
            />
          </div>
          <div className="form-group">
            <label>Focus</label>
            <select value={type} onChange={(e) => setType(e.target.value as SummaryType)}>
              <option value="full">Integrated (all trackers)</option>
              <option value="doctor">Doctor visits</option>
              <option value="mcas">MCAS episodes</option>
              <option value="medication">Medications & reactions</option>
              <option value="pain">Pain</option>
            </select>
          </div>
        </div>

        <button type="button" className="btn btn-primary btn-block" onClick={run} disabled={busy}>
          {busy ? 'Generating…' : 'Generate summary'}
        </button>

        {meta?.aiEnabled === false && (
          <div className="banner info" style={{ marginTop: 12 }}>
            OpenAI key not set on the function — you’re seeing a data snapshot only. Add <code>OPENAI_API_KEY</code> in Supabase Edge Function secrets.
          </div>
        )}

        {error && <div className="banner error" style={{ marginTop: 12 }}>{error}</div>}
      </div>

      {text && (
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', alignItems: 'center' }}>
            <h3 style={{ margin: 0 }}>Result</h3>
            <button type="button" className="btn btn-secondary" onClick={downloadTxt}>Download .txt</button>
          </div>
          <div className="summary-output" style={{ marginTop: 12 }}>{text}</div>
        </div>
      )}
    </div>
  )
}
